ModLuaFileAppend("mods/twitch_extended/config/rewards.lua", "mods/twitch_extended_example/files/scripts/add_point_reward.lua")
ModLuaFileAppend("mods/twitch_extended/config/rewards.lua", "mods/twitch_extended_example/files/scripts/add_sub_reward.lua")
ModLuaFileAppend("mods/twitch_extended/config/rewards.lua", "mods/twitch_extended_example/files/scripts/add_bit_reward.lua")
ModLuaFileAppend("mods/twitch_extended/config/loadouts.lua", "mods/twitch_extended_example/files/scripts/add_loadout.lua")
ModLuaFileAppend("mods/twitch_extended/config/run_modifiers.lua", "mods/twitch_extended_example/files/scripts/add_run_modifier.lua")